### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by stefanmd023**

### CODE REVIEW

**Comment by archi** [comment]
Thanks. As discussed on Telegram, I am not tooooo happy with pointing to a fuckup from a faq.
But I understand that most of the time valetudo is gone anyway when the autostart died.

I see these options (not exhaustive):
1. Keep mostly as is: If autostart died, point the user to do a manual upgrade as given on the website (maybe link directly to the website instead of another faq entry)
2. As suggested: Point to fuckup manual instead
3. Move the autostart to fuckup
4. Merge autostart with fuckup manual

I prefer the last one, but that's more of a intuition/opinion.

Let's see what @Hypfer likes most. At the end of the day, he has to be happy with how users are guided :)

**Comment by Hypfer** [comment]
What about duplicating the information from `autostart` in `manual` so that `manual` stays as is but `autostart` further contains all the steps to get the robot back up again?

**Comment by stefanmd023** [comment]
the autostart as it is now is more related to Dreame bots though isn't it? I tried to make the manual faq applicable to all bots as much as possible.

we could make the autostart more generic also

**Comment by stefanmd023** [comment]
OR since it is mostly referred to when someone posts that their robot lost valetudo (usually after a self-factory reset or an intentional factory reset) on dreame bots, we can make it a specific faq entry for this containing all the steps.

I was more thinking of having one entry refer to the other so as not to duplicate info :D bvut I guess that made it less practical

**Pull request merged**
